---
- src: git@git.smile.fr:ansible/ansible-genericservice.git
  scm: git
  version: 1.0.0

- src: git@git.smile.fr:ansible/ansible-basicserver.git
  scm: git
  version: 1.0.0

- src: git@git.smile.fr:ansible/ansible-redis.git
  scm: git
  version: 1.0.2

- src: git@git.smile.fr:ansible/ansible-mysql-server.git
  scm: git
  version: 1.0.0

#- src: git@git.smile.fr:ansible/ansible-elasticsearch.git
#  scm: git
#  version: 1.0.0

- src: git@git.smile.fr:ansible/ansible-nginx.git
  scm: git
  version: 1.0.0

- src: git@git.smile.fr:ansible/ansible-varnish.git
  scm: git
  version: 1.0.1

- src: git@git.smile.fr:ansible/ansible-apache.git
  scm: git
  version: 1.0.2

- src: git@git.smile.fr:ansible/ansible-php.git
  scm: git
  version: 1.0.0

- src: git@git.smile.fr:ansible/ansible-npm.git
  scm: git
  version: 1.0.0

- src: git@git.smile.fr:ansible/ansible-maildev.git
  scm: git
  version: 1.0.0

- src: git@git.smile.fr:ansible/ansible-postfix-satellite.git
  scm: git
  version: 1.0.0
